spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 8799
    url: jdbc:mysql://localhost:3306/spring cloud?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    show-sql: true
env:
  dev2
girl:
  name: Julia
  age: 18
